global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'tuficticio@infraticket.local'
        from: 'alertmanager@infraticket.local'
        smarthost: 'smtp:25'