groups:
- name: infraticket-alerts
  rules:

  - alert: ContainerDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Contenedor caído"
      description: "Un servicio está caído"

  - alert: HighCPU
    expr: sum(rate(container_cpu_usage_seconds_total{name!="/"}[1m])) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "CPU alta"
      description: "Uso de CPU elevado en contenedores"

  - alert: HighMemory
    expr: container_memory_usage_bytes{name!="/"} > 500000000
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Memoria alta"
      description: "Uso de RAM elevado"